// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.53.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "Projekte auflisten",
  description: "List manufacturing projects visible to the signed-in user, with optional text search, status filter and archive filter.",
  inputSchema: {
    search: z.string().nullable().describe("Optional text matched against customer, article number or article name."),
    status: z.number().int().nullable().describe("Optional numeric project status filter."),
    archived: z.boolean().nullable().describe("Optional archive filter; defaults to non-archived."),
    limit: z.number().int().min(1).max(100).nullable().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, archived, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("manufacturing_projects_with_status_label").select(
      "id, project_number, customer, artikel_nummer, artikel_bezeichnung, gesamtmenge, status, status_label, erste_anlieferung, letzte_anlieferung, archived, created_by_name, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    query = query.eq("archived", archived ?? false);
    if (status !== null && status !== void 0) query = query.eq("status", status);
    if (search) {
      const term = `%${search}%`;
      query = query.or(
        `customer.ilike.${term},artikel_nummer.ilike.${term},artikel_bezeichnung.ilike.${term}`
      );
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Projekt-Details",
  description: "Get one manufacturing project with all fields, by project id (UUID) or by project number.",
  inputSchema: {
    id: z2.string().uuid().nullable().describe("Project UUID. Use this or project_number."),
    project_number: z2.number().int().nullable().describe("Human-readable project number. Use this or id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, project_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!id && (project_number === null || project_number === void 0)) {
      return {
        content: [{ type: "text", text: "Provide either id or project_number." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("manufacturing_projects_with_status_label").select("*").limit(1);
    query = id ? query.eq("id", id) : query.eq("project_number", project_number);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Project not found or not visible to you." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool3({
  name: "list_tasks",
  title: "Aufgaben auflisten",
  description: "List tasks visible to the signed-in user, optionally filtered by project or status.",
  inputSchema: {
    project_id: z3.string().uuid().nullable().describe("Optional project UUID filter."),
    status: z3.string().nullable().describe("Optional task status filter (e.g. 'open', 'done')."),
    limit: z3.number().int().min(1).max(100).nullable().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("tasks").select("id, title, description, status, priority, due_date, project_id, assigned_to, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (project_id) query = query.eq("project_id", project_id);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_task_default = defineTool4({
  name: "create_task",
  title: "Aufgabe erstellen",
  description: "Create a task for a project on behalf of the signed-in user.",
  inputSchema: {
    project_id: z4.string().uuid().describe("UUID of the project the task belongs to."),
    title: z4.string().trim().min(1).describe("Short task title."),
    description: z4.string().nullable().describe("Optional longer description."),
    priority: z4.enum(["low", "medium", "high"]).nullable().describe("Optional priority; defaults to medium."),
    due_date: z4.string().nullable().describe("Optional due date as ISO date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ project_id, title, description, priority, due_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").insert({
      project_id,
      title,
      description: description ?? null,
      priority: priority ?? "medium",
      due_date: due_date ?? null,
      user_id: ctx.getUserId()
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/list-customers.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_customers_default = defineTool5({
  name: "list_customers",
  title: "Kunden auflisten",
  description: "List customers, optionally filtered by a name or number search term.",
  inputSchema: {
    search: z5.string().nullable().describe("Optional search term for customer name or number."),
    limit: z5.number().int().min(1).max(100).nullable().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("customers").select("*").limit(limit ?? 25);
    if (search) query = query.or(`name.ilike.%${search}%,customer_number.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-articles.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_articles_default = defineTool6({
  name: "list_articles",
  title: "Artikel auflisten",
  description: "List articles, optionally filtered by article number or name.",
  inputSchema: {
    search: z6.string().nullable().describe("Optional search term for article number or name."),
    limit: z6.number().int().min(1).max(100).nullable().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("articles").select("*").limit(limit ?? 25);
    if (search) {
      const term = `%${search}%`;
      query = query.or(`artikel_nummer.ilike.${term},artikel_bezeichnung.ilike.${term}`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
var whoami_default = defineTool7({
  name: "whoami",
  title: "Angemeldeter Benutzer",
  description: "Return the signed-in ProPlan user's profile, including display name and role.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("user_id, display_name, role").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const profile = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      display_name: data?.display_name ?? null,
      role: data?.role ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rhubaybwftyypfbiuoyc";
var mcp_default = defineMcp({
  name: "proplan",
  title: "proplan",
  version: "0.1.0",
  instructions: "Tools for ProPlan, a manufacturing planning app. Use `whoami` to see the signed-in user, `list_projects`/`get_project` for manufacturing projects and their status, `list_tasks`/`create_task` for project tasks, and `list_customers`/`list_articles` for master data. All data is scoped to the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_projects_default,
    get_project_default,
    list_tasks_default,
    create_task_default,
    list_customers_default,
    list_articles_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
