// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhubaybwftyypfbiuoyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJodWJheWJ3ZnR5eXBmYml1b3ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTczMjQsImV4cCI6MjA2OTYzMzMyNH0.mJxggdz01A4AiGgAmZFEHtXlzMHtr1AvNGjxLGj-f8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});